# This is a basic workflow to help you get started with Actions

name: Climate Data CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.MD'
      - '.github/workflows/**'
      - 'report/**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test Climate Data Store
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Check for MATLAB code issues in the project.
      - name: Check for MATLAB code issues
        uses: matlab-actions/run-command@v1
        if: always()
        with:
          command: addpath("buildutil"),codecheckToolbox()     

      # Commit the badge for the releases tested
      - name: commit code issues badge JSON
        if: always()
        env:
          WORKFLOW: ${{ env.GITHUB_WORKFLOW }}
          ACTOR: ${{ env.GITHUB_ACTOR }}
        run: |
          git config user.name "${WORKFLOW} by ${ACTOR}"
          git config user.email "<>"
          git commit report/badge/code_issues.json -m "Update code issues badge"
          git fetch
          git push
          
      # Runs all tests in the project.
      - name: Run tests
        uses: matlab-actions/run-command@v1
        if: always()
        with:
          command: addpath("buildutil"),testToolbox()     

      - name: Upload code coverage report to Codecov (https://app.codecov.io/gh/mathworks/climatedatastore)
        uses: codecov/codecov-action@v3
        with:
          files: report/codecoverage.xml
          
      # Publish test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "report/test-results.xml"
          
     # Save the contents of the report directory as an artifact
      - name: Save Report Directory
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: report
