# Release Climate Data Store Toolbox across all supported releases of MATLAB, package toolbox, create release

name: MATLAB Release

# Run workflow when a tag is created
on:
  push:
    tags: 
      - '*'

jobs:
  # This workflow contains:
  # 1. a matrixed test job run across a bunch of releases of MATLAB
  # 2. a reporting job that summarizes the tests, and updates release badge
  test:
    strategy:
      fail-fast: false
      matrix:
        MATLABVersion: [R2020a, R2020b, R2021a, R2021b, R2022a, R2022b]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.MATLABVersion }}

      # Runs all tests in the project.  Put results in a version specific subdirectory
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("buildutil"),testToolbox('ReportSubdirectory',"${{ matrix.MATLABVersion }}")     

      # Upload code coverage information to Codecov
      - name: Upload code coverage report to Codecov (https://app.codecov.io/gh/mathworks/climatedatastore)
        uses: codecov/codecov-action@v3
        with:
          files: report/codecoverage.xml
          env_vars: ${{ matrix.MATLABVersion }}

      # Save the contents of the report directory from each release into a single artifact.  Since each release makes their own directory, they all update the same artifact.
      - name: Save Report Directory
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: report
          
  # Report on what releases tested successfully.
  report:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Copy all the reports down into the container
      - uses: actions/download-artifact@v3
        with:
          name: report
          path: report

      # Generate the JSON for the releases tested badge
      - name: Generate tested with badge
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("buildutil"),badgesforToolbox()     

      # Commit the JSON for the releases tested badge
      - name: commit changed files
        if: always()
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"
          git commit report/badge/tested_with.json -m "Update tested with releases badge"
          git fetch
          git push
          
      # Publish test results from all the releases
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "report/*/test-results.xml"

  # Generate a draft release based on the tag
  release:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Package the MLTBX
      - name: Package Toolbox
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("buildutil"),packageToolbox("specific","${{  github.ref_name }}")     

      # Save the MLTBX.
      - name: Save Packaged Toolbox
        uses: actions/upload-artifact@v3
        with:
          name: Climate_Data_Store_Toolbox_for_MATLAB.mltbx
          path: release/Climate_Data_Store_Toolbox_for_MATLAB.mltbx

      # Create the release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          draft: true        
          artifacts: "release/Climate_Data_Store_Toolbox_for_MATLAB.mltbx"
          generateReleaseNotes: true
